number = {"-"? ~ ASCII_DIGIT+ }

line = { number ~ "," ~  number }
hid = { ASCII_DIGIT+ }
op = { (!";" ~ ANY)+ }
args = { hid ~ ("," ~ hid)* }
meta = { dim1 ~ "," ~ dim2 ~ "," ~ nrow ~ "," ~ ncol ~ "," ~ nnz }

dim1 = { number }
dim2 = { number }
nrow = { number }
ncol = { number }
nnz = { number }

hop = {line ~ ";" ~ hid ~ ";" ~ op ~ ";" ~ args? ~ ";" ~ meta ~ ";"}

hops = { (hop ~ ("\r\n" | "\n"))+ }

file = { SOI ~ (hops ~ ("\r\n" | "\n"))* ~ EOI }
